import type { Metadata } from "next";
import {Toaster } from 'react-hot-toast';
import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full bg=white">
    
      <body className={`${outfit.variable}' antialiased'`}>
        {children}
        <Toaster 
          position="top-right"
        />
      </body>
    </html>
  );
}
